all:

run_backend:
	@echo run the backend main.py
	python3 server/main.py

create_environment:
	@echo create a virtual environment with python3
	python3.12 -m venv .venv
	@echo activate the virtual environment
	source .venv/bin/activate
	@echo install the requirements
	pip install -r requirements.txt

