version: '3'
services:
  # Frontend React.js
  frontend:
    image: node:14
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    command: npm start

  # Backend Python com FastAPI
  backend:
    image: python:3.9
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  # MongoDB
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
